version: "3.7"

services:
  db:
    image: nosdaemon/mysql5
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/backup:/backup
    ports:
      - 3306:3306

secrets:
  mysql_root_password:
    file: ./mysql_root_password
  my_other_secret:
    external: true
